### ISSUE TITLE
Waveshare scanner - documentation required

### ISSUE THREAD

**Issue by bavarianledger** [cryptoadvance/specter-diy#1]
Could you provide more information on the Waveshare scanner:
how to configure it, what to solder and how to connect it?

**Comment by stepansnigirev** [comment]
I will close it for now. If something is still unclear - reopen it plz.

**Comment by bavarianledger** [comment]
Thank you.
It's working here!
![specter-diy](https://user-images.githubusercontent.com/48831982/65411036-1bcdc000-ddec-11e9-8af8-23c81b3db65a.png)
