### ISSUE TITLE
Show firmware version on settings page

### ISSUE THREAD

**Issue by ben-kaufman** [cryptoadvance/specter-diy#106]
Would be useful to be able to see the firmware version on the settings page, maybe add it in the note field under the title there?

**Comment by bitcoinheiro** [comment]
Agree, tested it a bit (with my limited version here) - without the cryptoadvance smartcard module - and it's working as expected. Bootloader ok, upgrade ok, save and load from microSD ok...

**Comment by stepansnigirev** [comment]
Should be available in the next release - added in https://github.com/cryptoadvance/specter-diy/commit/c066cea1b5a76e69b4ef1f18354da31a701ed779
