### ISSUE TITLE
Crashes during Signing -  Memory allocation failed

### ISSUE THREAD

**Issue by flyingfaders** [cryptoadvance/specter-diy#115]
When attempting to sign a txn via QR codes Specter-DIY crashes and displays the following error.

<img width="535" alt="specter_error" src="https://user-images.githubusercontent.com/67905545/103238619-5fc05500-499f-11eb-88a7-e3201c5b22bf.png">

Setup:
3 of 5
Tnx: 3 inputs, 1 output (to self, consolidating) 

I didn't test using USB(HWI) as I'm trying to maintain an airgap but I was able to sign the transaction via USB using Screen  on an airgapped computer.

**Comment by stepansnigirev** [comment]
Thanks for reporting!
I'll work on some optimizations for the next release.

QR code display implementation is not optimal at the moment, this can cause memory allocation errors when processing large transactions. Also, PSBT transaction is stored in MCU memory, but some parts of it can be moved to SDRAM.

**Comment by stepansnigirev** [comment]
Should be fixed with https://github.com/cryptoadvance/specter-diy/commit/a5477ee2c08076eeff160b371433d578772bdab6
It will be available in the next release (next week)

**Comment by flyingfaders** [comment]
Works perfectly on the latest release. Thanks!
