### ISSUE TITLE
correct Pin-code check seem to be buggy

### ISSUE THREAD

**Issue by k9ert** [cryptoadvance/specter-diy#127]
![image](https://user-images.githubusercontent.com/117085/111695920-e9abeb80-8833-11eb-8f4b-ee6511324292.png)

![image](https://user-images.githubusercontent.com/117085/111760157-ac307800-889e-11eb-81de-f7bc07b2d424.png)

**Comment by stepansnigirev** [comment]
Fixed in https://github.com/cryptoadvance/specter-diy/commit/ec583cba5b73e20ffeb0a8c90b11aeffc478e42d
