### ISSUE TITLE
BIP39 passphrase keyboard is missing some basic punctiation

### ISSUE THREAD

**Issue by stevenroose** [cryptoadvance/specter-diy#128]
I was testing the DIY today (really cool device, I love the smartcard feature!) and noticed that the BIP39 passphrase prompt was missing come basic punctuation characters like a dash or a dot.

**Comment by bitcoinheiro** [comment]
Agree. Would be great to have all chars from the ASCII table. Noticed the following missing:
37  %
46  .
60  <
61  =
62  >
94  ^
96  `
123  {
124  |
125  }
126  ~

**Comment by stepansnigirev** [comment]
Good catch! Fixed in https://github.com/cryptoadvance/specter-diy/commit/04246ceb5ebedc889b97c73269e6191497d23acb
Release with this fix is out already:
https://github.com/cryptoadvance/specter-diy/releases/latest
