### ISSUE TITLE
The specter-diy always restart

### ISSUE THREAD

**Issue by outshrill** [cryptoadvance/specter-diy#159]
When I plug it always retart once after 30 secs. It happened in version 1.4 and still happening after upgrade to last version.

**Comment by stepansnigirev** [comment]
Do you use a bare discovery board or a DIY with the shield? How do you power the board - from microUSB, miniUSB or external battery?

**Comment by outshrill** [comment]
After reading your comment I tried changing from micro to mini, and other batteries and finally it looks like it was a problem with the miniusb cable. tyvm for your help
