### ISSUE TITLE
Sign transaction via QR scanner

### ISSUE THREAD

**Issue by vitali-dev** [cryptoadvance/specter-diy#198]
Thanks for the great opensource project I have assembled the SpecterDIY and loaded the latest firmware v.1.6.2.

For this I created a test seed and saved it on the device and exported the XPUB to different wallets. 
Now when I want to sign a transaction under Sparrow or BlueWallet and scan it with the QR scanner I get the following message:

Host error - Can't find matching app for this request 

I can sign the exported PBST via the MicroSD in SpecterDIY without any problems.
Is my QR scanner not working?

**Comment by stepansnigirev** [comment]
It is working. In blue wallet enable legacy QR code encoding, in sparrow no idea.
They use bc-ur2 format that we don't support yet.
