### ISSUE TITLE
Save combined, complete PSBT to SD card

### ISSUE THREAD

**Issue by dimaatmelodromru** [cryptoadvance/specter-diy#200]
BTCPayServer expects a fully signed, complete PSBT to be provided in a PSBT file.
Please consider updating this behavior.

**Comment by stepansnigirev** [comment]
Made partial compression so that btcpay server devs can avoid calling `combinepsbt`
https://github.com/cryptoadvance/specter-diy/commit/b58a819ef09b2bca880a82c7e122618944355118#diff-7b400396286ca69f96020871327f1998a1184d9347656b258dc2df28d906c3cfR782
