### ISSUE TITLE
Feature request: import seedphrase via QR-code plate/paper

### ISSUE THREAD

**Issue by kravens** [cryptoadvance/specter-diy#207]
For easy importing of seedphrases the SeedQR has been recently popularized by the SeedSigner project: https://github.com/SeedSigner/seedsigner/blob/dev/docs/seed_qr/README.md

It is an open source project with well documented specifications for implementing SeedQR in other projects like Specter DIY.
I would love it if my Specter DIY could also use the same SeedQR plates/papers, as it would be perfect for an error self-correcting backup (up to 7%).

**Comment by stepansnigirev** [comment]
Implemented in 071208a214598cbee3614f833f3b95a3ee43987e
Will be released today.
