### ISSUE TITLE
Error displaying crypto-psbt QR

### ISSUE THREAD

**Issue by dimaatmelodromru** [cryptoadvance/specter-diy#217]
Note m > n in "Part m of n" on the attached photo![image](https://user-images.githubusercontent.com/4951450/186273035-111a1f05-fee1-4ba6-822c-9f70e4fca4c7.jpeg)

**Comment by stepansnigirev** [comment]
This is not an error. This is how ur2 format works - it has an infinite number of QR codes, each next contains a combination of previous. https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md
