### ISSUE TITLE
Updating firmware on DISCO

### ISSUE THREAD

**Issue by mcsnubbs** [cryptoadvance/specter-diy#70]
Does something need to be erased before transferring a new bin file to the device? I'm getting an error that there is not enough space on the device to transfer the new .bin file. Attempted to format/erase but having difficulty there as well. Thanks

**Comment by stepansnigirev** [comment]
I transferred this issue to specter-diy repo because it's about specter-diy :)

**Comment by stepansnigirev** [comment]
I assume it worked. I close this issue, if you still have problems - please reopen.
