### ISSUE TITLE
Enhancement: make a bip85 app for deterministic entropy

### ISSUE THREAD

**Issue by stepansnigirev** [cryptoadvance/specter-diy#72]
We have apps structure now, so we could develop an "app" that implements deterministic entropy derivation according to [BIP-85](https://github.com/bitcoin/bips/blob/master/bip-0085.mediawiki).
App has access to the keystore, so it could derive new seeds or WIFs or whatever from the root key of the keystore and show it on the screen. Completely stateless, no data storage, no communication with the host - only a GUI menu.

**Comment by xavierfiechter** [comment]
https://github.com/ethankosakovsky/bip85

**Comment by stepansnigirev** [comment]
Added implementation to embit, except RSA. Gonna implement in DIY soon-ish:
https://github.com/diybitcoinhardware/embit/pull/35

**Comment by jdlcdl** [comment]
I've left a comment at the following url. https://github.com/diybitcoinhardware/embit/commit/41f0a38f83f9df77bee7e0ddece4b32e3d935879

**Comment by stepansnigirev** [comment]
implemented in #265
