### ISSUE TITLE
[Feature request] Add user (active) input to seed creation process

### ISSUE THREAD

**Issue by bitcoinheiro** [cryptoadvance/specter-diy#79]
I understand that the seed is generated automagically using user input/interaction with the board before the seed generation button is pressed. Assuming every user has a different PIN and different handling, this should be enough from the technical perspective.

Anyway, it would be nice to be able to be more active on the seed creation process by adding entropy (and even seeing feedback of how that entropy affects the seed?)

I find the Specter DIY quite nice for this process, as a secure seed generator, a dedicated Ian Coleman BIP-39 tool: https://iancoleman.io/bip39/
![image](https://user-images.githubusercontent.com/50273260/92441202-79eae300-f1b6-11ea-9c6d-93ce2bb7f4e7.png)

Openoms also referred to another project that is using the raspi for this: https://www.rudefox.io/burrow/

He puts a great point here for adding this feature, it really makes the difference for people that don't trust hardware: https://www.rudefox.io/blog/2020-07-16-show-my-work.html

He even adds a sheet so people can verify if their dice entropy is actually being used for the seed creation:
https://www.rudefox.io/custody/walkthrough/create-seed/lookup-tables.pdf

![image](https://user-images.githubusercontent.com/50273260/92441821-90456e80-f1b7-11ea-9491-84433e9b8274.png)

Would be great to see something like this in the Specter DIY

**Comment by ChristopherA** [comment]
We are looking into doing this in LetheKit (we already support dice input that is compatible with Ian Coleman’s). If there is interest in supporting this then we should consider working on making all of these approaches of “deterministic randomness” a security reviewable standard.

**Comment by bitcoinheiro** [comment]
I believe this issue has been closed with the new checksum fix feature. No need to use the random number generator at all. Great feature BTW, love it! Cheers
